baseURL = "https://sangeetmishra.in/"
title = "Sangeet"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 12

pygmentsStyle = "dracula"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "sangeet259-github-io"

[params]
    author = "Sangeet Mishra"
    description = "Sangeet Mishre's personal website"
    keywords = "blog,developer,personal"
    info = "Curious Homo Sapien"
    avatarURL = "images/avatar.jpg"
    #gravatar = "john.doe@example.com"
    # footerContent = "Enter a text here."

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2018

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "dark"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Enable rendering of emojis
    enableEmoji = true

    # Custom CSS
    customCSS = ['css/custom.css']

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
[params.cloudflare]
    token = "token"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/sangeet259/"

[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/sangeetmishra_"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/sangeet259/"

[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram"
    weight = 4
    url = "https://instagram.com/sangeetmishra_/"

[[params.social]]
    name = "Medium"
    icon = "fa fa-medium"
    weight = 5
    url = "https://medium.com/@sangeet.mishra"



[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Posts"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Categories"
            weight = 3
            url = "categories/"

            [[languages.en.menu.main]]
            name = "T.I.L"
            weight = 4
            url = "til/"

            [[languages.en.menu.main]]
            name = "Résumé"
            weight = 6
            url = "/resume.pdf"